// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeN1eo7ZfdiG2RA6FD9DohKU8LP3qJpnY',
    appId: '1:335492309326:web:dd38ea3785f52749f17e1f',
    messagingSenderId: '335492309326',
    projectId: 'cuc-haul-a-day',
    authDomain: 'cuc-haul-a-day.firebaseapp.com',
    storageBucket: 'cuc-haul-a-day.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7-ub-JU1WHaKTmes_A2RBlHOmQI_Co6s',
    appId: '1:335492309326:android:5a1c929dcf7f2b37f17e1f',
    messagingSenderId: '335492309326',
    projectId: 'cuc-haul-a-day',
    storageBucket: 'cuc-haul-a-day.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0jfPB6DiT-3L0FQn3HJYQhJbqg7ICFbU',
    appId: '1:335492309326:ios:6969c83293a8b45ff17e1f',
    messagingSenderId: '335492309326',
    projectId: 'cuc-haul-a-day',
    storageBucket: 'cuc-haul-a-day.appspot.com',
    iosBundleId: 'com.example.haulADayWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0jfPB6DiT-3L0FQn3HJYQhJbqg7ICFbU',
    appId: '1:335492309326:ios:b67c702654d84a23f17e1f',
    messagingSenderId: '335492309326',
    projectId: 'cuc-haul-a-day',
    storageBucket: 'cuc-haul-a-day.appspot.com',
    iosBundleId: 'com.example.haulADayWeb.RunnerTests',
  );
}
